spring.application.name=demo
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=recipedb
spring.mongodb.username=root
spring.mongodb.password=1234
spring.mongodb.authentication-database=admin